theme: jekyll-theme-midnight
author: Yonah Aviv
title: FragmentQR
icon: https://github.com/y330/FragmentQR/blob/master/FragmentQR/img/32.png
description: Browser extension that allows for the generation of QR codes linking to arbitrary text on a page
show_downloads: True
navigation:
  - title: Home
    url: /index.md
  - title: Download Chrome Extension 
    url: https://chrome.google.com/webstore/detail/fragmentqr/cabodnfakameckfbbgkciiifempglloj
